# Ben Kabongo
# October 2025


ACCEPTED_TOPICS = {

    "Toys": [
        "age", 
        "assembly", 
        "battery", 
        "durability", 
        "educational", 
        "engagement", 
        "functionality", 
        "materials", 
        "price", 
        "safety"
    ],

    "Clothes": [
        "appearance",
        "care",
        "comfort",
        "construction",
        "functionality",
        "fit",
        "material",
        "price",
        "service",
        "shipping"
    ],

    "Beauty": [
        "color", 
        "compatibility", 
        "efficacy", 
        "ingredients", 
        "longevity", 
        "packaging", 
        "price", 
        "scent", 
        "service", 
        "texture"
    ],

    "Sports": [
        "comfort", 
        "durability", 
        "fit", 
        "material", 
        "performance", 
        "portability", 
        "price",
        "safety", 
        "service", 
        "usability"
    ],

    "Cell": [
        "battery",
        "camera",
        "display",
        "durability",
        "performance",
        "price",
        "service",
        "software",
        "specs",
        "usability",
    ]
    
}


TOPIC_MAPPING = {

    "Toys": {
        'portability': 'assembly',
        'size': 'assembly',
        'theme': 'engagement',
        'difficulty': 'age',
        'duration': 'engagement',
        'gameplay': 'engagement',
        'fairness': 'engagement',
        'storyline': 'engagement',
        'social': 'engagement',
        'story': 'engagement',
        'quality': 'durability',
        'usage': 'engagement',
        'space': 'assembly',
        'value': 'price',
        'quantity': 'assembly',
        'speed': 'functionality',
        'compatibility': 'functionality',
        'stability': 'durability',
        'accessories': 'assembly',
        'size and completeness': 'assembly',
        'water resistance': 'durability',
        'range': 'functionality',
        'weight': 'assembly',
        'sound': 'functionality',
        'contents': 'assembly',
        'volume': 'functionality',
        'size and weight': 'assembly',
        'overall quality': 'durability',
        'quality control': 'durability',
        'capacity': 'assembly',
        'depth': 'assembly',
        'play value': 'engagement',
        'packaging': 'assembly',
        'replayability': 'engagement',
        'noise': 'functionality',
        'product quality': 'durability',
        'storage': 'assembly',
        'posability': 'functionality',
        'complexity': 'age',
        'fit': 'assembly',
        'waterproof': 'durability',
        'instructions': 'assembly',
        'noise level': 'functionality',
        'luck': 'engagement',
        'features': 'functionality',
        'performance': 'functionality',
        'price and value': 'price',
        'entertainment': 'engagement',
        'flexibility': 'functionality',
        'time': 'engagement',
        'reliability': 'durability',
        'poseability': 'functionality',
        'skill': 'age',
        'characters': 'engagement',
        'articulation': 'functionality',
        'user experience': 'engagement',
        'inclusion': 'assembly'
    },

    "Clothes": {
        'durability': 'construction',
        'size': 'fit',
        'color accuracy': 'appearance',
        'color': 'appearance',
        'water resistance': 'functionality',
        'temperature': 'functionality',
        'value': 'price',
        'colorfastness': 'care',
        'packaging': 'shipping',
        'length': 'fit',
        'waterproofing': 'functionality',
        'color retention': 'care',
        'style': 'appearance',
        'waterproof': 'functionality',
        'waterproofness': 'functionality',
        'warmth': 'functionality',
        'temperature regulation': 'functionality',
        'security': 'functionality',
        'longevity': 'construction',
        'temperature tolerance': 'functionality',
        'insulation': 'functionality',
        'cold resistance': 'functionality',
        'reliability': 'construction',
        'wear and tear': 'construction',
        'capacity': 'functionality',
        'seasonal usage': 'functionality',
        'breathability': 'comfort',
        'seasonality': 'functionality',
        'weather': 'functionality',
        'returns': 'service',
        'height': 'fit',
        'return': 'service',
        'temperature suitability': 'functionality',
        'inseam': 'fit',
        'traction': 'functionality',
        'water repellency': 'functionality',
        'thickness': 'material',
        'seasonal suitability': 'functionality',
        'temperature retention': 'functionality',
        'wind resistance': 'functionality',
        'waist': 'fit',
        'sleeve length': 'fit',
        'color options': 'appearance',
        'compatibility': 'functionality'
    },

    "Beauty": {
        'availability': 'service',
        'application': 'texture',
        'brand': 'service',
        'size': 'packaging',
        'overall': 'efficacy',
        'projection': 'scent',
        'general': 'efficacy',
        'value': 'price',
        'sturdiness': 'packaging',
        'refillability': 'packaging',
        'general opinion': 'efficacy',
        'design': 'packaging',
        'durability': 'packaging',
        'brand reputation': 'service',
        'accessories': 'packaging',
        'quantity': 'packaging',
        'sillage': 'scent',
        'weight': 'packaging',
        'shape': 'packaging',
        'reputation': 'service',
        'comfort': 'texture',
        'purpose': 'efficacy',
        'irritation': 'compatibility',
        'capacity': 'packaging',
        'product overall': 'efficacy',
        'general impression': 'efficacy',
        'moisture': 'efficacy',
        'portability': 'packaging',
        'authenticity': 'service',
        'intensity': 'color',
        'waterproof': 'longevity',
        'protection': 'efficacy',
        'conditioning': 'efficacy',
        'construction': 'packaging',
        'cooling': 'efficacy',
        'overall impression': 'efficacy',
        'product design': 'packaging'
    },

    "Sports": {
        'security': 'safety',
        'maintenance': 'usability',
        'size': 'fit',
        'value': 'price',
        'storage': 'portability',
        'weight': 'portability',
        'reusability': 'durability',
        'reliability': 'durability',
        'seller': 'service',
        'feel': 'comfort',
        'stability': 'safety',
        'grip': 'performance',
        'repair': 'usability',
        'balance': 'performance',
        'instructions': 'usability',
        'functionality': 'performance',
        'accuracy': 'performance',
        'care': 'usability',
        'cleanability': 'usability',
        'cleaning': 'usability',
        'noise reduction': 'performance',
        'sensitivity': 'performance',
        'warranty': 'service',
        'light coverage': 'performance',
        'audio': 'performance',
        'battery life': 'performance',
        'delivery': 'service',
        'length': 'fit'
    },

    "Cell": {
        'accessory quality': 'usability',
        'accessories': 'usability',
        'reliability': 'durability',
        'accessory': 'usability',
        'adapter': 'usability',
        'cables': 'usability',
        'touch quality': 'display',
        'warranty': 'service',
        'repair': 'service',
        'functionality': 'performance',
        'range': 'specs',
        'bluetooth': 'specs',
        'pairing': 'specs',
        'stylus': 'usability',
        'music headset': 'usability',
        'cable length': 'usability',
        'control': 'usability',
        'storage': 'specs',
        'keyboard': 'usability',
        'leather': 'durability',
        'build quality': 'durability',
        'pen': 'usability',
        'fit': 'usability',
        'hd dock': 'usability',
        'hd station': 'usability',
        'battery charger': 'battery',
        'nfc': 'specs',
        'solar charging': 'battery',
        'cable': 'usability',
        'location/web': 'specs',
        'security': 'software',
        'value': 'price',
        'function': 'performance',
        'wireless': 'specs',
        'headphones': 'usability',
        'charging': 'battery',
        'wireless charger': 'battery',
        'apps': 'software',
        'os': 'software',
        'controls': 'usability',
        'wireless charging': 'battery',
        'construction': 'durability',
        'network': 'specs',
        'screen': 'display',
        'wfi': 'specs',
        'convenience': 'usability',
        'flashlight': 'usability',
        'water resistance': 'durability'
    }

}
